export enum ChatActions {
    CREATE_ROOM = 'CREATE_ROOM',
    JOIN_ROOM = 'JOIN_ROOM',
    LEAVE_ROOM = 'LEAVE_ROOM',
    GET_ROOMS = 'GET_ROOMS',
    GET_HISTORY = 'GET_HISTORY',
    SEND_MESSAGE = 'SEND_MESSAGE',
    DELETE_ROOM = 'DELETE_ROOM',
    UPDATE_ROOM = 'UPDATE_ROOM',
    ADD_MEMBER = 'ADD_MEMBER',
    REMOVE_MEMBER = 'REMOVE_MEMBER'
}